#!/usr/bin/env bash
# Private Cloud Gateway — one-command installer for Oracle Cloud Ubuntu VM
# Usage: curl -fsSL https://raw.githubusercontent.com/NathanWalash/private-cloud-gateway/main/install.sh | sudo bash

set -euo pipefail

REPO="https://github.com/NathanWalash/private-cloud-gateway.git"
INSTALL_DIR="/opt/pcg"
SERVICE_NAME="pcg"
MIN_UBUNTU="22"

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[PCG]${NC} $*"; }
success() { echo -e "${GREEN}[PCG]${NC} $*"; }
warn()    { echo -e "${YELLOW}[PCG]${NC} $*"; }
error()   { echo -e "${RED}[PCG]${NC} $*" >&2; exit 1; }

# ── Checks ────────────────────────────────────────────────────────────────────
[ "$(id -u)" -eq 0 ] || error "Run as root: curl ... | sudo bash"

OS=$(lsb_release -si 2>/dev/null || echo "Unknown")
VER=$(lsb_release -sr 2>/dev/null | cut -d. -f1 || echo "0")
[ "$OS" = "Ubuntu" ] && [ "$VER" -ge "$MIN_UBUNTU" ] || \
  error "Requires Ubuntu ${MIN_UBUNTU}+. Got: ${OS} ${VER}"

info "Starting Private Cloud Gateway installation on Ubuntu ${VER}"

# ── Install dependencies ──────────────────────────────────────────────────────
info "Installing system dependencies..."
apt-get update -qq
apt-get install -y -qq curl git ca-certificates gnupg lsb-release jq openssl ufw

# Docker
if ! command -v docker &>/dev/null; then
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
  success "Docker installed"
else
  success "Docker already installed ($(docker --version))"
fi

# Docker Compose (plugin)
if ! docker compose version &>/dev/null; then
  info "Installing Docker Compose plugin..."
  apt-get install -y -qq docker-compose-plugin
fi
success "Docker Compose: $(docker compose version --short)"

# ── Collect configuration ────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Private Cloud Gateway Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -rp "  Your root domain (e.g. nathan.me): " DOMAIN
read -rp "  Admin email for Let's Encrypt (cert expiry notices): " ADMIN_EMAIL

# Validate inputs
[[ "$DOMAIN" =~ ^[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?)+$ ]] \
  || error "Invalid domain: $DOMAIN"
[[ "$ADMIN_EMAIL" =~ ^[^@]+@[^@]+\.[^@]+$ ]] \
  || error "Invalid email: $ADMIN_EMAIL"

SESSION_SECRET=$(openssl rand -hex 32)
SETUP_TOKEN=$(openssl rand -hex 16)
BACKUP_PASSPHRASE=$(openssl rand -hex 24)

echo ""

# ── Set up directory layout ──────────────────────────────────────────────────
info "Creating directory layout at $INSTALL_DIR..."
mkdir -p \
  "$INSTALL_DIR/data" \
  "$INSTALL_DIR/backups" \
  "$INSTALL_DIR/blueprints" \
  "$INSTALL_DIR/caddy/data" \
  "$INSTALL_DIR/caddy/config"

chmod 700 "$INSTALL_DIR/data" "$INSTALL_DIR/backups"

# ── Clone or update repository ───────────────────────────────────────────────
if [ -d "$INSTALL_DIR/.git" ]; then
  info "Updating existing installation..."
  git -C "$INSTALL_DIR" pull --ff-only
else
  info "Cloning repository..."
  git clone --depth 1 "$REPO" "$INSTALL_DIR"
fi

# ── Resolve the release image to pin ──────────────────────────────────────────
# Pin PCG_VERSION to the latest published release so the first boot pulls a real,
# immutable image instead of a floating :latest.
info "Resolving latest release..."
PCG_VERSION=$(curl -fsSL https://api.github.com/repos/NathanWalash/private-cloud-gateway/releases/latest 2>/dev/null \
  | grep -m1 '"tag_name"' | cut -d'"' -f4)
[ -z "$PCG_VERSION" ] && PCG_VERSION=latest
info "Deploying version $PCG_VERSION"

# ── Write .env ───────────────────────────────────────────────────────────────
info "Writing configuration..."
cat > "$INSTALL_DIR/.env" <<EOF
# Private Cloud Gateway — production configuration
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

CLOUD_CORE_ENV=production
CLOUD_CORE_PORT=8080

# Pinned release image tag (deploy.sh updates this on deploy/rollback).
PCG_VERSION=$PCG_VERSION
CLOUD_CORE_COOKIE_DOMAIN=$DOMAIN
CLOUD_CORE_LOGIN_URL=https://home.$DOMAIN/login
CLOUD_CORE_ADMIN_EMAIL=$ADMIN_EMAIL

CLOUD_CORE_DATABASE_PATH=/data/cloud-core.db
CLOUD_CORE_SESSION_SECRET=$SESSION_SECRET
CLOUD_CORE_CADDY_ADMIN=caddy:2019

# Setup token — required to claim the admin account on first run.
# This closes the first-run race: without it, anyone reaching the exposed
# instance before you could create the admin account. Printed once below.
CLOUD_CORE_SETUP_TOKEN=$SETUP_TOKEN
CLOUD_CORE_BLUEPRINT_DIR=/blueprints

# Backup passphrase — encrypts every backup. Generated below; SAVE IT (you need
# it to restore). Losing it means losing access to your backups.
CLOUD_CORE_BACKUP_PASSPHRASE=$BACKUP_PASSPHRASE

# Scheduled backups — e.g. "24h" for daily, empty to disable.
CLOUD_CORE_BACKUP_SCHEDULE=24h
# How many backup archives to keep (older ones are pruned). 0 keeps all.
CLOUD_CORE_BACKUP_KEEP=7

# Bootstrap (optional — use the setup wizard instead)
# CLOUD_CORE_BOOTSTRAP_EMAIL=
# CLOUD_CORE_BOOTSTRAP_PASSWORD=
EOF
chmod 600 "$INSTALL_DIR/.env"
success ".env written"

# ── Write production Caddyfile ───────────────────────────────────────────────
cp "$INSTALL_DIR/infra/caddy/Caddyfile.prod" "$INSTALL_DIR/caddy/Caddyfile"
info "Production Caddyfile written"

# ── Install systemd service ──────────────────────────────────────────────────
info "Installing systemd service..."
sed "s|/opt/pcg|$INSTALL_DIR|g" \
  "$INSTALL_DIR/infra/oracle/pcg.service" \
  > "/etc/systemd/system/${SERVICE_NAME}.service"

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
success "systemd service installed and enabled"

# ── Configure firewall ───────────────────────────────────────────────────────
info "Configuring firewall..."
bash "$INSTALL_DIR/infra/oracle/setup-firewall.sh"

# ── Start service ─────────────────────────────────────────────────────────────
info "Starting Private Cloud Gateway..."
systemctl start "$SERVICE_NAME"

# Wait for health
for i in $(seq 1 30); do
  if curl -sf "http://localhost:8080/healthz" &>/dev/null; then
    break
  fi
  sleep 2
done

if curl -sf "http://localhost:8080/healthz" &>/dev/null; then
  success "Service is healthy"
else
  warn "Service may still be starting. Check: sudo journalctl -u $SERVICE_NAME -f"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  ${GREEN}Private Cloud Gateway installed successfully!${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Dashboard: https://home.$DOMAIN"
echo ""
echo -e "  ${YELLOW}Setup token (needed to create your admin account):${NC}"
echo -e "      ${GREEN}$SETUP_TOKEN${NC}"
echo "  Enter this on the setup screen. It's also in $INSTALL_DIR/.env"
echo "  (CLOUD_CORE_SETUP_TOKEN). Keep it secret until setup is complete."
echo ""
echo -e "  ${YELLOW}Backup passphrase (SAVE THIS — required to restore backups):${NC}"
echo -e "      ${GREEN}$BACKUP_PASSPHRASE${NC}"
echo "  Stored in $INSTALL_DIR/.env (CLOUD_CORE_BACKUP_PASSPHRASE)."
echo ""
echo "  Next steps:"
echo "  1. In the Oracle Cloud console, add ingress rules to your subnet's"
echo "     Security List for TCP 80 and 443 (only 22 is open by default),"
echo "     or the site is unreachable and HTTPS can't be issued."
echo "  2. Point DNS: A $DOMAIN → $(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo 'YOUR_IP')"
echo "     and:        A *.$DOMAIN → same IP"
echo "  3. Visit https://home.$DOMAIN to complete setup (enter the token above)"
echo ""
echo "  Manage:"
echo "  sudo systemctl status $SERVICE_NAME"
echo "  sudo journalctl -u $SERVICE_NAME -f"
echo ""
